#!/bin/bash

#cd /var/www/net/rexlib
#rex -u root -H "10.15.0.3" UtilSSH:install_openssh_user_sshkey --user=ttt
#rex -d -u root -H "bikini.uwc.local" UtilRex:uptime
#rex -u root -H "srv-echo.uwc.local" Virt:list_vm
#rex Check:diagnose --host=gwknskust --ticket --ticket_from=uuu@uwc.ufanet.ru
#rex Check:diagnose --host=gwknskust 
#rex -u root -H "bikini.uwc.local" Cert:install --cert=/tmp/cert.pem --key=/tmp/key.pem
#rex -d -u root -H "bikini.uwc.local" UtilRex:uptime

#rex -H 10.0.1.1 UtilRex:dump_system_information
#rex -H 10.0.1.1 UtilSSH:install_openssh_sshkey
#rex -H 10.0.1.1 Deploy:Owrt:show_router
#rex -H 10.0.1.1 Deploy:Erebus:System:configure --confhost=erebus
rex -H 192.168.12.3 Deploy:Erebus:deploy_router

#rex UtilSSH:root_cleanup_known_hosts_ip --ip=10.14.73.27
#rex -u ural -s -S test -H 10.14.73.27 UtilSSH:install_openssh_user_sshkey --user=root
#rex -u root -H 10.14.73.27 UtilSSH:install_openssh_user_sshkey --user=root
#rex -u root -H 10.14.73.27 Deploy:Simple:deploy_srv

echo "Exit code: $?."
