# This file is autogenerated. All changes will be overwritten!

config ipsec
  option debug 0
  #option install_routes 1
  option install_virtual_ip 0
  option routing_table 30000
  option routing_table_prio 30000
  list ignore_routing_tables r_beeline
  #list interface wan

#config remote 'testgateway'
#  option enabled 1
#  option gateway '10.2.77.88'
#  option authentication_method 'psk'
#  option pre_shared_key 'TESTKEY'
#  list crypto_proposal 'testgateway_prop'
#  list tunnel 'testlan0'
#
#config tunnel 'testlan0'
#  #option mode 'route'
#  option local_subnet '0.0.0.0/0'
#  option remote_subnet '192.168.1.0/24'
#  option ikelifetime '28800s'
#  option lifetime '12h'
#  #option dpdaction 'restart'
#  #option dpddelay '30s'
#  option keyexchange 'ikev1'
#  option compress 1
#  list crypto_proposal 'testgateway_prop'
#
# use same proposals for p1 and p2
#config p1_proposal 'testgateway_prop'
#  option encryption_algorithm '3des'
#  option hash_algorithm 'sha1'
#  option dh_group modp1024


