# This file is autogenerated. All changes will be overwritten!
# This file is interpreted as shell script.
# Put your custom tc rules here, they will
# be executed with each firewall (re-)start.

command -v tc >/dev/null || exit 1

tc qdisc del dev vpn1 root 2>/dev/null
tc qdisc add dev vpn1 root handle 1: pfifo

